## load the labour force dataset and extract the unemployment rate of different states.

In [4]:
import pandas as pd

In [13]:
file_path = r"./datatset/6202012-Labour_force.xlsx"
df = pd.read_excel(file_path, sheet_name=2)

In [14]:
df.head()

,Unnamed: 0,Employment to population ratio ; > Females ; > Western Australia ;,Employment to population ratio ; > Females ; > Tasmania ;,Employment to population ratio ; > Females ; > Tasmania ;.1,Employment to population ratio ; > Females ; > Tasmania ;.2,Employment to population ratio ; > Females ; > Northern Territory ;,Employment to population ratio ; > Females ; > Northern Territory ;.1,Employment to population ratio ; > Females ; > Australian Capital Territory ;,Employment to population ratio ; > Females ; > Australian Capital Territory ;.1,Unemployed total ; Persons ; Australia ;,...,> Unemployment rate looked for full-time work ; > Males ; > Queensland ;,> Unemployment rate looked for full-time work ; > Males ; > South Australia ;,> Unemployment rate looked for full-time work ; > Males ; > Western Australia ;,> Unemployment rate looked for full-time work ; > Males ; > Tasmania ;,> Unemployment rate looked for full-time work ; > Males ; > Northern Territory ;,> Unemployment rate looked for full-time work ; > Males ; > Australian Capital Territory ;,> Unemployment rate looked for full-time work ; > Females ; Australia ;,> Unemployment rate looked for full-time work ; > Females ; Australia ;.1,> Unemployment rate looked for full-time work ; > Females ; Australia ;.2,> Unemployment rate looked for full-time work ; > Females ; > New South Wales ;
0,Unit,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,000,...,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent
1,Series Type,Original,Trend,Seasonally Adjusted,Original,Trend,Original,Trend,Original,Trend,...,Original,Original,Original,Original,Original,Original,Trend,Seasonally Adjusted,Original,Original
2,Data Type,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,STOCK,...,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [19]:
# Filter columns that contain 'Employment' in their names and drop them
labour_force_df = df
columns_to_drop = [col for col in labour_force_df.columns if 'Employment' in col]
labour_force_df_cleaned = labour_force_df.drop(columns=columns_to_drop)

# Check the first few rows of the cleaned dataframe
labour_force_df_cleaned.head()

,Unnamed: 0,Unemployed total ; Persons ; Australia ;,Unemployed total ; Persons ; Australia ;.1,Unemployed total ; Persons ; Australia ;.2,Unemployed total ; Persons ; > New South Wales ;,Unemployed total ; Persons ; > New South Wales ;.1,Unemployed total ; Persons ; > New South Wales ;.2,Unemployed total ; Persons ; > Victoria ;,Unemployed total ; Persons ; > Victoria ;.1,Unemployed total ; Persons ; > Victoria ;.2,...,> Unemployment rate looked for full-time work ; > Males ; > Queensland ;,> Unemployment rate looked for full-time work ; > Males ; > South Australia ;,> Unemployment rate looked for full-time work ; > Males ; > Western Australia ;,> Unemployment rate looked for full-time work ; > Males ; > Tasmania ;,> Unemployment rate looked for full-time work ; > Males ; > Northern Territory ;,> Unemployment rate looked for full-time work ; > Males ; > Australian Capital Territory ;,> Unemployment rate looked for full-time work ; > Females ; Australia ;,> Unemployment rate looked for full-time work ; > Females ; Australia ;.1,> Unemployment rate looked for full-time work ; > Females ; Australia ;.2,> Unemployment rate looked for full-time work ; > Females ; > New South Wales ;
0,Unit,000,000,000,000,000,000,000,000,000,...,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent
1,Series Type,Trend,Seasonally Adjusted,Original,Trend,Seasonally Adjusted,Original,Trend,Seasonally Adjusted,Original,...,Original,Original,Original,Original,Original,Original,Trend,Seasonally Adjusted,Original,Original
2,Data Type,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,...,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [20]:
# Get the columns that have "Trend" or "Seasonally Adjusted" in row 1 (which is index 1 in pandas)
columns_to_drop = labour_force_df_cleaned.columns[(labour_force_df_cleaned.iloc[1] == "Trend") | (labour_force_df_cleaned.iloc[1] == "Seasonally Adjusted")]

# Drop the identified columns
labour_force_df_cleaned = labour_force_df_cleaned.drop(columns=columns_to_drop)

# Check the first few rows of the cleaned dataframe
labour_force_df_cleaned.head()

,Unnamed: 0,Unemployed total ; Persons ; Australia ;.2,Unemployed total ; Persons ; > New South Wales ;.2,Unemployed total ; Persons ; > Victoria ;.2,Unemployed total ; Persons ; > Queensland ;.2,Unemployed total ; Persons ; > South Australia ;.2,Unemployed total ; Persons ; > Western Australia ;.2,Unemployed total ; Persons ; > Tasmania ;.2,Unemployed total ; Persons ; > Northern Territory ;.1,Unemployed total ; Persons ; > Australian Capital Territory ;.1,...,> Unemployment rate looked for full-time work ; > Males ; > New South Wales ;,> Unemployment rate looked for full-time work ; > Males ; > Victoria ;,> Unemployment rate looked for full-time work ; > Males ; > Queensland ;,> Unemployment rate looked for full-time work ; > Males ; > South Australia ;,> Unemployment rate looked for full-time work ; > Males ; > Western Australia ;,> Unemployment rate looked for full-time work ; > Males ; > Tasmania ;,> Unemployment rate looked for full-time work ; > Males ; > Northern Territory ;,> Unemployment rate looked for full-time work ; > Males ; > Australian Capital Territory ;,> Unemployment rate looked for full-time work ; > Females ; Australia ;.2,> Unemployment rate looked for full-time work ; > Females ; > New South Wales ;
0,Unit,000,000,000,000,000,000,000,000,000,...,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent,Percent
1,Series Type,Original,Original,Original,Original,Original,Original,Original,Original,Original,...,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original
2,Data Type,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,...,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT,PERCENT
3,Frequency,Month,Month,Month,Month,Month,Month,Month,Month,Month,...,Month,Month,Month,Month,Month,Month,Month,Month,Month,Month
4,Collection Month,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [21]:
output_path = r"./datatset/unemployment_of_all_states.csv"
labour_force_df_cleaned.to_csv(output_path, index=False)

In [2]:
#do employment of different industry.

In [40]:
file_path = r"./datatset/6291005-employmnet_rate_of_different_industry.xlsx"
df = pd.read_excel(file_path, sheet_name=2)

In [7]:
df.head()

,Unnamed: 0,"> South Australia ; Electricity, Gas, Water and Waste Services ; > Employed full-time ;","> South Australia ; Electricity, Gas, Water and Waste Services ; > Employed part-time ;",> South Australia ; Construction ; Employed total ;,> South Australia ; Construction ; > Employed full-time ;,> South Australia ; Construction ; > Employed part-time ;,> South Australia ; Wholesale Trade ; Employed total ;,> South Australia ; Wholesale Trade ; > Employed full-time ;,> South Australia ; Wholesale Trade ; > Employed part-time ;,> South Australia ; Retail Trade ; Employed total ;,...,"> Australian Capital Territory ; Electricity, Gas, Water and Waste Services ; > Employed full-time ;","> Australian Capital Territory ; Electricity, Gas, Water and Waste Services ; > Employed part-time ;",> Australian Capital Territory ; Construction ; Employed total ;,> Australian Capital Territory ; Construction ; > Employed full-time ;,> Australian Capital Territory ; Construction ; > Employed part-time ;,> Australian Capital Territory ; Wholesale Trade ; Employed total ;,> Australian Capital Territory ; Wholesale Trade ; > Employed full-time ;,> Australian Capital Territory ; Wholesale Trade ; > Employed part-time ;,> Australian Capital Territory ; Retail Trade ; Employed total ;,> Australian Capital Territory ; Retail Trade ; > Employed full-time ;
0,Unit,000,000,000,000,000,000,000,000,000,...,000,000,000,000,000,000,000,000,000,000
1,Series Type,Original,Original,Original,Original,Original,Original,Original,Original,Original,...,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original
2,Data Type,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,...,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK
3,Frequency,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,...,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter
4,Collection Month,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

In [41]:
# Filter columns that contain 'Western Australia'
filtered_df = df.loc[:, df.columns.str.contains("Western Australia")]

# Display the first few rows of the filtered DataFrame
print(filtered_df.head())

  > Western Australia ;  Agriculture, Forestry and Fishing ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Agriculture, Forestry and Fishing ;  > Employed full-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Agriculture, Forestry and Fishing ;  > Employed part-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Mining ;  Employed total ;  \
0                                               000
1                                          Original
2                                             STOCK
3                                           Quarter
4                                                 2

  > Western Australia ;  Mining ;  > Employed full-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Mining ;  > Employed part-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Manufacturing ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Manufacturing ;  > Employed full-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Manufacturing ;  > Employed part-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Electricity, Gas, Water and Waste Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

   ...  \
0  ...
1  ...
2  ...
3  ...
4  ...

  > Western Australia ;  Health Care and Social Assistance ;  > Employed part-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Arts and Recreation Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Arts and Recreation Services ;  > Employed full-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Arts and Recreation Services ;  > Employed part-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Other Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Other Services ;  > Employed full-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Other Services ;  > Employed part-time ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Employed total ;  \
0                                     000
1                                Original
2                                   STOCK
3                                 Quarter
4                                       2

  > Western Australia ;  > Employed full-time ;  \
0                                           000
1                                      Original
2                                         STOCK
3                                       Quarter
4                                             2

  > Western Australia ;  > Employed part-time ;
0                                           000
1                                      Original
2                                         STOCK
3                                       Quarter
4                                             2

[5 rows x 60 columns]

In [42]:
df = filtered_df

# Filter columns that contain 'Western Australia' and exclude those with 'part-time' or 'full-time'
filtered_df = df.loc[:, df.columns.str.contains("Western Australia", case=False) & 
                     ~df.columns.str.contains("part-time|full-time", case=False)]

# Display the first few rows of the filtered DataFrame
print(filtered_df.head())

  > Western Australia ;  Agriculture, Forestry and Fishing ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Mining ;  Employed total ;  \
0                                               000
1                                          Original
2                                             STOCK
3                                           Quarter
4                                                 2

  > Western Australia ;  Manufacturing ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Electricity, Gas, Water and Waste Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Construction ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Wholesale Trade ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Retail Trade ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Accommodation and Food Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Transport, Postal and Warehousing ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Information Media and Telecommunications ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Financial and Insurance Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Rental, Hiring and Real Estate Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Professional, Scientific and Technical Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Administrative and Support Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Public Administration and Safety ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Education and Training ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Health Care and Social Assistance ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Arts and Recreation Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Other Services ;  Employed total ;  \
0                                                000
1                                           Original
2                                              STOCK
3                                            Quarter
4                                                  2

  > Western Australia ;  Employed total ;
0                                     000
1                                Original
2                                   STOCK
3                                 Quarter
4                                       2

In [43]:
import pandas as pd

# Load the Excel file
file_path = "./datatset/6291005-employmnet_rate_of_different_industry.xlsx"
df = pd.read_excel(file_path, sheet_name=2)

# Filter columns that contain 'Western Australia' and exclude those with 'part-time' or 'full-time'
filtered_df = df.loc[:, df.columns.str.contains("Western Australia", case=False) & 
                     ~df.columns.str.contains("part-time|full-time", case=False)]

# Add the first column of the original df to filtered_df
filtered_df.insert(0, df.columns[0], df.iloc[:, 0])

# Save the result to a CSV file
filtered_df.to_csv("wa_employment_data.csv", index=False)

print("Filtered data saved as 'filtered_employment_data.csv'")

Filtered data saved as 'filtered_employment_data.csv'

In [ ]:
import pandas as pd

# Load the saved CSV file with filtered data
file_path = "./datatset/filtered_employment_data.csv"
filtered_df = pd.read_csv(file_path)

# Load the original Excel file again
original_file_path = "./datatset/6291005-employmnet_rate_of_different_industry.xlsx"
df = pd.read_excel(original_file_path, sheet_name=2)

# Specify the columns you want to add by name or by index
# Example: Adding more columns by names
additional_columns = ["Column_Name_1", "Column_Name_2"]  # Replace with actual column names

# Alternatively, add by column indices (e.g., add columns at index 1 and 2)
# additional_columns = df.columns[[1, 2]]  # Uncomment this line if using indices

# Add these columns to the filtered_df
for col in additional_columns:
    filtered_df[col] = df[col]

# Save the updated DataFrame to a new CSV
filtered_df.to_csv("./dataset/updated_filtered_employment_data.csv", index=False)

print("Updated filtered data saved as 'updated_filtered_employment_data.csv'")

In [17]:
import pandas as pd

# Load the filtered CSV and the original Excel file (sheet 1 for additional columns)
filtered_path = "./datatset/employment_data.csv"
original_path = "./datatset/6291005-employmnet_rate_of_different_industry.xlsx"
filtered_df = pd.read_csv(filtered_path)
df_sheet1 = pd.read_excel(original_path, sheet_name=1)

# Ensure the "date" column in sheet 1 matches with filtered_df
merged_df = pd.merge(filtered_df, df_sheet1.iloc[:, :59], on="Unnamed: 0", how="left")

# Print the heading of the 59th column for verification
print("The 59th column header:", df_sheet1.columns[58])


merged_df.to_csv("./datatset/employment_data.csv", index=False)

The 59th column header: Australia ;  Employed total ;

In [19]:
import pandas as pd

# Load the updated CSV file
file_path = "./datatset/employment_data.csv"
updated_df = pd.read_csv(file_path)

# Remove columns that contain 'part-time' or 'full-time'
cleaned_df = updated_df.loc[:, ~updated_df.columns.str.contains("part-time|full-time", case=False)]

# Save the cleaned DataFrame to a new CSV
cleaned_df.to_csv("./datatset/employment_data.csv", index=False)

print("Cleaned data saved as 'cleaned_employment_data.csv'")

Cleaned data saved as 'cleaned_employment_data.csv'

In [20]:
file_path = "./datatset/employment_data.csv"
updated_df = pd.read_csv(file_path)

In [22]:
updated_df.head()

,Unnamed: 0,"> Western Australia ; Agriculture, Forestry and Fishing ; Employed total ;",> Western Australia ; Mining ; Employed total ;,> Western Australia ; Manufacturing ; Employed total ;,"> Western Australia ; Electricity, Gas, Water and Waste Services ; Employed total ;",> Western Australia ; Construction ; Employed total ;,> Western Australia ; Wholesale Trade ; Employed total ;,> Western Australia ; Retail Trade ; Employed total ;,> Western Australia ; Accommodation and Food Services ; Employed total ;,"> Western Australia ; Transport, Postal and Warehousing ; Employed total ;",...,Australia ; Financial and Insurance Services ; Employed total ;,"Australia ; Rental, Hiring and Real Estate Services ; Employed total ;","Australia ; Professional, Scientific and Technical Services ; Employed total ;",Australia ; Administrative and Support Services ; Employed total ;,Australia ; Public Administration and Safety ; Employed total ;,Australia ; Education and Training ; Employed total ;,Australia ; Health Care and Social Assistance ; Employed total ;,Australia ; Arts and Recreation Services ; Employed total ;,Australia ; Other Services ; Employed total ;,Australia ; Employed total ;
0,Unit,000,000,000,000,000,000,000,000,000,...,000,000,000,000,000,000,000,000,000,000
1,Series Type,Original,Original,Original,Original,Original,Original,Original,Original,Original,...,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original
2,Data Type,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,...,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK
3,Frequency,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,...,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter
4,Collection Month,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

In [33]:
import pandas as pd

# Load the employment data CSV
file_path = "./datatset/employment_data.csv"
employment_df = pd.read_csv(file_path)

# Keep only the first 20 columns
restored_df = employment_df.iloc[:, :20]

# Save the restored DataFrame back to a new CSV
restored_df.to_csv("./datatset/employment_data.csv", index=False)

print("Restored data saved as 'restored_employment_data.csv'")

Restored data saved as 'restored_employment_data.csv'

In [32]:
import pandas as pd

# Load the filtered CSV and the original Excel file (sheet 1 for additional columns)
filtered_path = "./datatset/employment_data.csv"
original_path = "./datatset/6291005-employmnet_rate_of_different_industry.xlsx"
filtered_df = pd.read_csv(filtered_path)
df_sheet1 = pd.read_excel(original_path, sheet_name=1)

# Convert date columns in both DataFrames to a common date format (ignoring the time)
filtered_df['date'] = pd.to_datetime(filtered_df['Unnamed: 0'], errors='coerce').dt.date
df_sheet1['date'] = pd.to_datetime(df_sheet1['Unnamed: 0'], errors='coerce').dt.date

# Merge the DataFrames on the 'date' column
merged_df = pd.merge(filtered_df, df_sheet1.iloc[:, :59], on="Unnamed: 0", how="left")

# Remove columns that contain 'part-time' or 'full-time'
cleaned_df = merged_df.loc[:, ~merged_df.columns.str.contains("part-time|full-time", case=False)]

# Save the cleaned DataFrame to a new CSV
cleaned_df.to_csv("./datatset/employment_data.csv", index=False)

print("Cleaned data saved as 'cleaned_employment_data.csv'")

Cleaned data saved as 'cleaned_employment_data.csv'

In [36]:
import pandas as pd

# Load the Excel file and select the first 59 columns from sheet 1
original_path = "./datatset/6291005-employmnet_rate_of_different_industry.xlsx"
df_sheet1 = pd.read_excel(original_path, sheet_name=1).iloc[:, :59]


cleaned_df =df_sheet1.loc[:, ~merged_df.columns.str.contains("part-time|full-time", case=False)]

cleaned_df.head()

IndexError: Boolean index has wrong length: 79 instead of 59

In [38]:
cleaned_df =df_sheet1.loc[:, ~df_sheet1.columns.str.contains("part-time|full-time", case=False)]

cleaned_df.head()

,Unnamed: 0,"Australia ; Agriculture, Forestry and Fishing ; Employed total ;",Australia ; Mining ; Employed total ;,Australia ; Manufacturing ; Employed total ;,"Australia ; Electricity, Gas, Water and Waste Services ; Employed total ;",Australia ; Construction ; Employed total ;,Australia ; Wholesale Trade ; Employed total ;,Australia ; Retail Trade ; Employed total ;,Australia ; Accommodation and Food Services ; Employed total ;,"Australia ; Transport, Postal and Warehousing ; Employed total ;",...,Australia ; Financial and Insurance Services ; Employed total ;,"Australia ; Rental, Hiring and Real Estate Services ; Employed total ;","Australia ; Professional, Scientific and Technical Services ; Employed total ;",Australia ; Administrative and Support Services ; Employed total ;,Australia ; Public Administration and Safety ; Employed total ;,Australia ; Education and Training ; Employed total ;,Australia ; Health Care and Social Assistance ; Employed total ;,Australia ; Arts and Recreation Services ; Employed total ;,Australia ; Other Services ; Employed total ;,Australia ; Employed total ;
0,Unit,000,000,000,000,000,000,000,000,000,...,000,000,000,000,000,000,000,000,000,000
1,Series Type,Original,Original,Original,Original,Original,Original,Original,Original,Original,...,Original,Original,Original,Original,Original,Original,Original,Original,Original,Original
2,Data Type,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,...,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK,STOCK
3,Frequency,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,...,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter,Quarter
4,Collection Month,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2

In [39]:
cleaned_df.to_csv("./datatset/au_employment_data.csv", index=False)